apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.appConfig }}
  {{ $key | nindent 2 }}: {{ $value | quote }}
{{- end }}