apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $port := .Values.service.ports }}
    - protocol: TCP
      port: {{ . }}
      targetPort: {{ . }}
      name: {{ . | quote}}
    {{- end }}
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
